#  Copyright ⓒ 2018-2019 ThePhD.
#
#  Distributed under the Boost Software License, Version 1.0. (See
#  accompanying file LICENSE or copy at
#  http://www.boost.org/LICENSE_1_0.txt)
#
#  See http://www.boost.org/libs/out_ptr/ for documentation.


sudo: required
language: cpp

git:
  depth: 2

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
- mkdir out_ptr-build-debug
- cd out_ptr-build-debug
- cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBOOST_OUT_PTR_TESTS=ON -DBOOST_OUT_PTR_EXAMPLES=ON
- cmake --build . --config Debug
- ctest --output-on-failure --build-config Debug
- cd ..
- mkdir out_ptr-build-release
- cd out_ptr-build-release
- cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBOOST_OUT_PTR_TESTS=ON -DBOOST_OUT_PTR_EXAMPLES=ON
- cmake --build . --config Release
- ctest --output-on-failure --build-config Release

matrix:
  fast_finish: true
      
notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never
